import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import LocomotiveProvider from "./Components/LocomotiveProvider";
const inter = Inter({ subsets: ["latin"] });
import LocomotiveScrollProvider from "./context/LocomotiveScrollContext"

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <LocomotiveProvider>

        </LocomotiveProvider> */}
        <LocomotiveScrollProvider>

          {children}
        </LocomotiveScrollProvider>
      </body>
    </html>
  );
}
