import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import LocomotiveProvider from "./Components/LocomotiveProvider";
const inter = Inter({ subsets: ["latin"] });
import LocomotiveScrollProvider from "./context/LocomotiveScrollContext"
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};
import { Provider } from "react-redux";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>


    //     {children}
    //   </body>
    // </html>

    <ClerkProvider>

      <html lang="en">
        <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
